### PR TITLE
ci: remove workaround for free-threaded build w. maturin

### PR DESCRIPTION
**Pull request by davidhewitt**
Should hopefully just work on the new maturin 1.7.5 🤞

### CODE REVIEW

**Comment by davidhewitt** [comment]
I opened https://github.com/PyO3/maturin/pull/2324 and https://github.com/PyO3/maturin/pull/2325 to resolve.

**Comment by davidhewitt** [comment]
@messense looks like there is no way to run `Maturin-action` with a git branch of `maturin`? I guess I can temporarily fork.

**Comment by messense** [comment]
> looks like there is no way to run `maturin-action` with a git branch of `maturin`

Yes, but for Windows and macOS you can just `pip install` from a git branch of maturin to test as there are no Docker containers involved.

**Comment by davidhewitt** [comment]
Ok, it looks like `maturin` 1.7.6 builds the wheels totally fine, however the metadata-version bump to 2.4 broke twine. https://github.com/pypa/twine/issues/1146

I can deal with that separately, at least for the non-abi3 wheels I ship it seems like `maturin` is now ready, and https://github.com/PyO3/maturin/pull/2333 hopefully fixes the abi3 case 🎉

**Pull request merged**
