### PR TITLE
drop lexical-core dependency

### LINKED ISSUE #49: Consider migrating away from the lexical_core crate
Hi! I am the maintainer of pydantic and pydantic-core in Fedora Linux that now require this crate. jitter depends on lexical_core to parse floats. lexical has [multiple soundness/safety issues](https://rustsec.org/advisories/RUSTSEC-2023-0055.html) and is no longer actively maintained. We would thus prefer not to package it in Fedora. Would it be possible for jitter to use a different crate for this purpose?

See also: the list of alternative libraries in [RUSTSEC-2023-0055](https://rustsec.org/advisories/RUSTSEC-2023-0055.html)

### PR DESCRIPTION
**Pull request by davidhewitt**
Closes #49 

Let's see how this affects benchmarks...

### CODE REVIEW

**Comment by davidhewitt** [comment]
Well, this works but it does come at a performance regression. Potentially one solution is to use `minimal-lexical`, but that doesn't seem any better than using any of the rest of the (seemingly unmaintained) lexical family.

Another option is to add our own implementation of float parsing and not use either `std` or `lexical`.

**Comment by samuelcolvin** [comment]
I think it looks like serde has extracted the bits of lexical that it needs into their own package.

I think we should either:
* use a third party package
* see if serde makes the methods we would need public, and use them?
* copy and paste the bits of lexical we need into here - this might mean we could reuse the part of the float before the `.` which we've already parsed

**Comment by musicinmybrain** [comment]
Just adding a direct cross-reference to related PR https://github.com/pydantic/jiter/pull/57.

**Comment by davidhewitt** [comment]
Yes, let's close this for now, can always revisit later.

**Pull request closed without merging**
