### PR TITLE
faster creation of `PyList`

### PR DESCRIPTION
**Pull request by samuelcolvin**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
This makes a big difference locally, but codspeed seems to disagree

image

???

**Comment by davidhewitt** [comment]
Is "locally" arm or x86_64? Might differ greatly between the two platforms.

TBH I'm ok with this but I also just think that really PyO3 should be reworking its list constructor to allow this.

**Review by davidhewitt — APPROVED** [review]

**Comment by samuelcolvin** [comment]
Locally was macos.

**Comment by samuelcolvin** [comment]
Not clear there's an improvement on x86, might even be worse (although I have no idea how it could be):

image

So I'll leave this, we can either reconsider or close.

**Comment by davidhewitt** [comment]
I think better is that I aim to fix PyO3 to avoid needless reference count operations. Would be a modest speedup for quite a few operations / smaller binary size :)

**Comment by davidhewitt** [comment]
PyO3 0.23 (#137) has a new `IntoPyObject` trait which optimises transfer of reference counts, will close this.

**Pull request closed without merging**
