### PR TITLE
move from lexical-core to depend on lexical-parse-float directly

### LINKED ISSUE #49: Consider migrating away from the lexical_core crate
Hi! I am the maintainer of pydantic and pydantic-core in Fedora Linux that now require this crate. jitter depends on lexical_core to parse floats. lexical has [multiple soundness/safety issues](https://rustsec.org/advisories/RUSTSEC-2023-0055.html) and is no longer actively maintained. We would thus prefer not to package it in Fedora. Would it be possible for jitter to use a different crate for this purpose?

See also: the list of alternative libraries in [RUSTSEC-2023-0055](https://rustsec.org/advisories/RUSTSEC-2023-0055.html)

### PR DESCRIPTION
**Pull request by decathorpe**
Closes #49.

Code changes are minimal - I have adjusted the `use` statement to import things under the same names as previously, and only one line of actual code needs to be changed - the `parse_partial_with_options` function is from `lexical-core`, but it is a trivial one-line function, so it can just be replaced with calling the trait method on f64 directly.

### CODE REVIEW

**Review by samuelcolvin — APPROVED** [review]
LGTM, I'll let @davidhewitt review and approve.

**Comment by decathorpe** [comment]
Sorry about the formatting, I forgot to run rustfmt after my changes.

If I read the benchmark results correctly, this small change actually speeds things up measurably? That's interesting ... well, it's one fewer function call, so the code can probably be more optimized.

**Comment by samuelcolvin** [comment]
I'm not sure if we have good float benchmarks?

**Review by davidhewitt — APPROVED** [review]

**Comment by davidhewitt** [comment]
LGTM, thanks!

**Comment by davidhewitt** [comment]
To summarise my opinion here: I think at some point we might want to remove the `lexical` dependency entirely, but this is good enough for downstream packaging for now. So we can postpone the bigger work until we have the resources to also maintain performance.

**Comment by davidhewitt** [comment]
`lexical` crates are maintained again and have a 1.0 (see #182), so I think no need to remove any more.

**Pull request merged**
